# -*- coding: utf-8 -*-
"""meeting minutes generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrvJKD_5ndaBnJBnPjQl-vzYiqoNzaqj
"""

# Meeting Minutes Generator

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

# User Inputs
meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma separated): ")
agenda = input("Enter agenda points (comma separated): ")
decision = input("Enter decision taken (comma separated): ")
action_items = input("Enter action items (comma separated): ")
prepared_by = input("prepared by: ")

# Process Inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decision_list = [d.strip() for d in decision.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]

# Create structured metting minutes
minutes = {
    "Meeting Tittle": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda": "; ".join(decision_list),
    "Prepared By": prepared_by,
    "Generated on": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

# Convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting Minutes Generated successfully\n")
display(df)

# Save as csv
df.to_csv("meeting_minutes.cvs",index=False)
print("\n File saved as meeting-minutes.csv")