# -*- coding: utf-8 -*-
"""torch pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DiXoHa9WK162swyRnKFHaUVAjVjLrXt
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd

#Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")

#Sample product review(you can change only this text later)
reviews = """The laptop starts quickly and works smoothly for daily tasks
The screen quality is clear and good for watching videos
Battery backup is average and needs charging aften
The fan makes noise when many apps are running
Overall,it is good laptop for students but not for gaming
"""

#Split review into sentences
sentences = [s.strip() for s in reviews.splitlines() if s.strip()] # Changed to splitlines() to handle newline-separated sentences

all_pros = []
all_cons = []

for s in sentences:
    if s == "":
        continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        all_pros.append(s)
    elif result["label"] == "NEGATIVE":
        all_cons.append(s)

# Take only up to 2 pros and 2 cons from the collected lists
pros = all_pros[:2]
cons = all_cons[:2]

# Ensure both lists have a length of 2 for DataFrame creation, padding with None if necessary
while len(pros) < 2:
    pros.append(None)
while len(cons) < 2:
    cons.append(None)

df = pd.DataFrame({
    "pros": pros,
    "cons": cons
  })
df